orders/urls.py
"""order URL Configuration """

from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'orders'



urlpatterns = [
    path("", views.index, name="index"),
    url(r'^menu/$', views.index, name="menu"),
    url(r'^cart/$', views.cart_item_list, name="cart"),
    path('cart/delete_item/<int:cartitem_id>', views.delete_cart_item, name="delete_cart_item"),
    path('cart/confirm_order', views.confirm_order, name='confirm_order'),
    path('cart/place_order', views.place_order, name='place_order'),
    path('user/history', views.order_history, name="order_history"),
    path('user/order_detail/<int:order_id>', views.order_detail, name="order_detail"),
    path('cart/add_item/<int:item_id>', views.add_item, name='add_item'),
    path('manage/order', views.manage_admin_order, name='manage_admin_order'),

]

pizza/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]



urlpatterns += staticfiles_urlpatterns()

orders/views.py
''' This view is used for showing the different view options '''
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import Pizza, Sub, Dinner, SubExtra, Topping, Salad, Pasta, BaseItem, IndividualCartItem, IndividualOrderItem, OrderDetail


#---------------------------------------------------------------------------
#
def get_menu_items(productlist):
    ''' this function creates a menu items for the product list as per its serving size.'''

    # generate list of unique item names.
    names = []
    for product in productlist:
        if product.name not in names:
            names.append(product.name)

    # Parse different sizes with corresponding product name
    items = []
    for name in names:
        item = {}
        item["name"] = name
        for product in productlist:
            try:
                if product.name == name and product.size == BaseItem.SMALL:
                    item['id_small'] = product.id
                    item['price_small'] = product.price
                elif product.name == name and product.size == BaseItem.LARGE:
                    item['id_large'] = product.id
                    item['price_large'] = product.price
            # if product has no size attribute (AttributeError)
            except:
                item['id'] = product.id
                item['price'] = product.price
        items.append(item)

    return items


def get_total_items_in_cart_count(request):
    ''' function to get total items in the cart '''
    if not request.user.is_authenticated:
        return 0
    cartitemscount = IndividualCartItem.objects.filter(user=request.user).count()
    return cartitemscount



# Create your views here.
# @login_required(login_url="/accounts/login/")
def index(request):
    ''' default page to show the menu '''
    context = {
        "regular_pizzas": get_menu_items(Pizza.objects.filter(crust=Pizza.REGULAR).all()),
        "sicilian_pizzas": get_menu_items(Pizza.objects.filter(crust=Pizza.SICILIAN).all()),
        "toppings": Topping.objects.all(),
        "subs": get_menu_items(Sub.objects.all()),
        "extras": get_menu_items(SubExtra.objects.all()),
        "pastas": Pasta.objects.all(),
        "salads": Salad.objects.all(),
        "dinners": get_menu_items(Dinner.objects.all())
        }
    # now set the item count in hte cart.
    context['item_in_cart_count'] = get_total_items_in_cart_count(request)
    return render(request, 'orders/menu.html', context)



@login_required(login_url='accounts:login')
def add_item(request, item_id):
    ''' Function to ask for adding a new item into cart.
    This will get post message from the form with updated data '''

    if request.method == 'GET':
        try:
            baseitem = BaseItem.objects.get(pk=item_id)
        except:
            return HttpResponseRedirect(reverse('menu'))

        context = {
            "item": baseitem,
        }

        # check if this is for pizza and it requires custom toppings
        if hasattr(baseitem, 'pizza') and baseitem.pizza.max_toppings > 0:
            context['toppings'] = Topping.objects.all()
            context['max_toppings'] = baseitem.pizza.max_toppings
        # check if this is for sub and can have extras
        elif hasattr(baseitem, 'sub'):
            context['extras'] = SubExtra.objects.filter(size=baseitem.size).all()

        # now set the item count in hte cart.
        context['item_in_cart_count'] = get_total_items_in_cart_count(request)
        return render(request, 'orders/add_item.html', context)

    # we are here this means we have received a post message command.
    # Hence lets add this item to our cart.
    try:
        baseitem = BaseItem.objects.get(pk=item_id)
    except:
        return HttpResponseNotFound()

    # lets get the basic data from the form.
    selquantity = int(request.POST['quantity'])
    totalprice = float(request.POST['total-price'])
    extrasubcount = int(request.POST.get('extra-sub-count', 0))
    add_to_cart_and_checkout = request.POST.get('add-to-cart-checkout', False)



    try:
        cart_item = IndividualCartItem.objects.create(user=request.user, baseitem=baseitem, quantity=selquantity)

        # Now check if we have toppings then try and set each topping data.
        max_toppings = 0
        if hasattr(baseitem, 'pizza') and baseitem.pizza.max_toppings > 0:
            max_toppings = baseitem.pizza.max_toppings

        for loopindex in range(max_toppings):
            toppingid = request.POST.get(f'topping-{loopindex+1}', False)
            if toppingid:
                toppingdata = Topping.objects.get(pk=toppingid)
                cart_item.toppings.add(toppingdata)

        for loopindex in range(extrasubcount):
            extraid = request.POST.get(f'extra-{loopindex+1}', False)
            if extraid:
                extradata = SubExtra.objects.get(pk=extraid)
                cart_item.subextra.add(extradata)

        cart_item.price = totalprice
        cart_item.save()

    except:
        cart_item.delete()
        return HttpResponseNotFound()

    if add_to_cart_and_checkout:
        return HttpResponseRedirect(reverse('orders:cart'))
    else:
        return HttpResponseRedirect(reverse('orders:menu'))



@login_required(login_url='accounts:login')
def cart_item_list(request):
    ''' Function to display the current cart items... '''
    cartitems = IndividualCartItem.objects.filter(user=request.user).all()

    context = {
        "cartitems": cartitems
    }

    # lets get the cart total.
    cart_total_cost = 0
    for item in cartitems:
        cart_total_cost += item.price

    context['cart_total_cost'] = cart_total_cost

    # now set the item count in hte cart.
    context['item_in_cart_count'] = get_total_items_in_cart_count(request)
    return render(request, 'orders/cartitemlist.html', context)



@login_required(login_url='accounts:login')
def delete_cart_item(request, cartitem_id):
    ''' Function to delete an item from the cart... '''

    if request.method == 'GET':
        return HttpResponseNotFound()

    try:
        cartitem = IndividualCartItem.objects.get(pk=cartitem_id)
        cartitem.delete()
    except IndividualCartItem.DoesNotExist:
        return HttpResponseNotFound()

    return HttpResponseRedirect(reverse('orders:cart'))





@login_required(login_url='accounts:login')
def confirm_order(request):
    ''' Function to place a new order from our current cart ... '''

    if request.method == 'GET':
        return HttpResponseNotFound()

    # first of all get the complete cart items.
    cartitems = IndividualCartItem.objects.filter(user=request.user).all()
    context = {
        "cartitems": cartitems
    }

    # lets get the cart total.
    cart_total_cost = 0
    for item in cartitems:
        cart_total_cost += item.price
    context['cart_total_cost'] = cart_total_cost

    # get the details from the form.
    context['contact'] = request.POST['contact']
    context['address'] = request.POST['address']
    context['message'] = request.POST['message']
    context['for_confimation_readonly'] = 'True'

    # do not set the cart item count here as in this case i donot want to show any item in cart.
    # context['item_in_cart_count'] = get_total_items_in_cart_count(request)
    return render(request, 'orders/cartitemlist.html', context)





@login_required(login_url='accounts:login')
def place_order(request):
    ''' Function to place a new order from our current cart ... '''

    if request.method == 'GET':
        return HttpResponseNotFound()

    # first of all get the complete cart items.
    cartitems = IndividualCartItem.objects.filter(user=request.user).all()

    # lets get the cart total.
    cart_total_cost = 0
    for item in cartitems:
        cart_total_cost += item.price

    # get the details from the form.
    contact = request.POST['contact']
    address = request.POST['address']
    message = request.POST['message']

    # now lets create the order..
    orderdetail = OrderDetail.objects.create(
        user=request.user,
        orderprice=cart_total_cost,
        contact=contact,
        address=address,
        message=message,
    )

    # now lets add each item of this cart in the order
    for item in cartitems:
        orderitem = IndividualOrderItem.objects.create(
            user=request.user,
            baseitem=item.baseitem,
            quantity=item.quantity,
            price=item.price
            )

        # now lets add each topping from the cart to this order
        for topping in item.toppings.all():
            orderitem.toppings.add(topping)

        # now lets add each extra from the cart to this order
        for extra in item.subextra.all():
            orderitem.subextra.add(extra)

        # we have completed the order item hence lets add this in our order
        orderdetail.orderitems.add(orderitem)

    # as we have completed our order hence lets delete this cart item.
    cartitems.delete()
    orderdetail.save()

    return HttpResponseRedirect(reverse('orders:order_history'))





@login_required(login_url='accounts:login')
def order_history(request):
    ''' Function to get the order history for this customer ... '''

    if request.method == 'POST':
        return HttpResponseNotFound()

    context = {
        "orders_list": OrderDetail.objects.filter(user=request.user).order_by('-ordertime')
    }

    # now set the item count in hte cart.
    context['item_in_cart_count'] = get_total_items_in_cart_count(request)
    return render(request, 'orders/order_history.html', context)




@login_required(login_url='accounts:login')
def order_detail(request, order_id):
    ''' Function to get the details of this order. Here we will validate that the order should belong to this customer... '''

    try:

orders/templates/orders/add_item.html
{% extends 'base_layout.html' %}

{% block head %}
{% load static %}
<script src="{% static 'orders/add_item.js' %}"></script>
{% endblock %}


{% block title %}{{ block.super }} - add item{% endblock %}


{% block content%}
<form action="{% url 'orders:add_item' item.id %}" method="POST">
    {% csrf_token %}
    <nav class="navbar sticky-top navbar-dark bg-dark justify-content-between">
        <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:menu' %}">Back to menu</a>
        <div>
        <input type="submit" name="add-to-cart" value="Add to Cart" class="btn btn-sm btn-success my-2 my-sm-0">
        <input type="submit" name="add-to-cart-checkout" value="Add to Cart & Checkout" class="btn btn-sm btn-success my-2 my-sm-0">
    </div>
    </nav>

    <h1>{{ item.name }}{% if item.size != '' %} - ({{item.size}}){% endif %}</h1>
    <!-- Get the individual item price -->
    <span id="individual-item-price" style="display: none;">{{ item.price }}</span>

    <!-- lets create a table with hidden borders so as to show the options. -->
    <table class="table table-striped">
        <colgroup>
            <col width="60%"></col>
            <col width="40%"></col>
        </colgroup>
        <tbody>
            <!-- set the quantity form element. -->
            <tr>
                <td>Quantity</td>
                <td><input name="quantity" id="quantity" type="number" value=1 min=1 max=10></td>
            </tr>
            
            <!-- we will get topping opion only if required -->
            {% if toppings and max_toppings > 0 %}
                {% with ''|center:max_toppings as range %}
                    {% for _ in range %}
                    <tr>
                        <td>Topping - {{ forloop.counter }}</td>
                        <td><select name="topping-{{forloop.counter}}">
                            {% for topping in toppings %}
                                <option value="{{ topping.id }}">{{ topping.name }}</option>
                            {% endfor %}</select></td>
                    </tr>
                    {% endfor %}
                {% endwith %}            
            {% endif%}

            <!-- we will get extra options only if required -->
            {% if extras %}
            {% for extra in extras %}
            <tr>
                <td>Extra {{ extra.name }} (+<span id="extra_price-{{extra.id}}">{{ extra.price }}</span>)</td>
                <td><input class="extrasub" name="extra-{{forloop.counter}}" value="{{ extra.id }}" id="extra-{{extra.id}}" type="checkbox"></td>
            </tr>
            {% endfor %}
            {% endif%}

            <!-- Now lets show the total price -->
            <tr style="font-weight:bold">
                <td>Total Price</td>
                <td><input name="total-price" readonly style="border: none; font-weight: bold;" value={{ item.price }}></td>
            </tr>
    
        </tbody>
    </table>

    <!-- Extra Hidden data in the form to show additional info -->
    {% if extras %}
    <input type="hidden" readonly name="extra-sub-count" value={{extras|length}} />
    {% else %}
    <input type="hidden" readonly name="extra-sub-count" value=0 />
    {% endif%}

</form>
{% endblock %}

orders/templates/orders/cartitemlist.html
{% extends 'base_layout.html' %}


{% block title %}{{ block.super }} - {% if for_confimation_readonly %}confirm order{% else %}cart{% endif %}{% endblock %}


{% block head %}
{% load static %}
<script src="{% static 'orders/cartitemlist.js' %}"></script>
{% endblock %}

{% block content%}
{% if cartitems and cartitems|length > 0 %}
    {% if for_confimation_readonly %}
    <nav class="navbar sticky-top navbar-dark bg-dark justify-content-between">
        <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:cart' %}">Modify order</a>
        <input type="button" value="Confirm & place order" class="btn btn-sm btn-success my-2 my-sm-0" onclick="fnCheckOut()">
    </nav>
    {% else %}
    <nav class="navbar sticky-top navbar-dark bg-dark justify-content-between">
        <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:menu' %}">Continue shopping</a>
        <input type="button" value="Checkout" class="btn btn-sm btn-success my-2 my-sm-0" onclick="fnCheckOut()">
    </nav>
    {% endif %}

<!-- lets create a table with hidden borders so as to show the options. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 40%">Item (Size)</th>
            <th scope="col" style="width: 10%">Quantity</th>
            <th scope="col" style="width: 10%">Cost</th>
            <th scope="col" style="width: 30%">Addons</th>
            {% if not for_confimation_readonly %}
            <th scope="col" style="width: 10%"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>

        {% for cartitem in cartitems %}
        <tr>
            <td>{% if cartitem.baseitem.pizza.crust %}{{ cartitem.baseitem.pizza.crust}} Pizza - {% endif %}
                {{ cartitem.baseitem.name }} {% if cartitem.baseitem.size %} ({{ cartitem.baseitem.size}} ){% endif %}
            </td>
            <td>{{ cartitem.quantity }}</td>
            <td>{{ cartitem.price }}</td>
            <td>{% if cartitem.toppings.count > 0 %}
                {% for topping in cartitem.toppings.all %}
                {% if forloop.last %}
                {{ topping.name }}
                {% else %}
                {{ topping.name }},
                {% endif %}
                {% endfor %}
                {% elif cartitem.subextra.count > 0 %}
                {% for extra in cartitem.subextra.all %}
                {% if forloop.last %}
                {{ extra.name }}
                {% else %}
                {{ extra.name }},
                {% endif %}
                {% endfor %}
                {% endif %}
            </td>
            {% if not for_confimation_readonly %}
            <td>
                <form action="{% url 'orders:delete_cart_item' cartitem.id %}" method="POST" onsubmit="return confirm('Are you sure you want to delete this entry ?');">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="btn btn-sm btn-outline-danger my-2 my-sm-0">
                </form>
            </td>
            {% endif %}
        </tr>
        {% endfor %}

        <!-- now lets write the cart total. -->
        <tr style="font-weight:bold">
            <td>Cart Total</td>
            <td></td>
            <td><span id="cart-total-cost">{{cart_total_cost}}</span></td>
            <td></td>
            {% if not for_confimation_readonly %}
            <td></td>
            {% endif %}
        </tr>
       
    </tbody>
</table>

<br>
<div class="row justify-content-center">
    <div style="width: 90%;">
            <form class="site-form" id="Customer-details-form" 
            {% if for_confimation_readonly %}
            action="{% url 'orders:place_order' %}" 
            {% else %}
            action="{% url 'orders:confirm_order' %}" 
            {% endif %}
            method="POST">

            {% csrf_token %}
            <h3>Custome details</h3>
            <div class="form-group">
                Contact* 
                {% if not for_confimation_readonly %}
                <small class="form-text text-muted" style="float: right ;">(Maximum length of 50 character)</small>
                {% endif %}
                <input class="form-control" name="contact" {% if contact %}value="{{contact}}" {%endif%} placeholder="Phone Number" required {% if for_confimation_readonly %} readonly {% endif %} maxlength="50" >
            </div>
            <div class="form-group">
                Address* 
                {% if not for_confimation_readonly %}
                <small class="form-text text-muted" style="float: right ;">(Maximum length of 100 character)</small>
                {% endif %}
                <input class="form-control" name="address" {% if address %}value="{{address}}" {%endif%} placeholder="Address" required {% if for_confimation_readonly %} readonly {% endif %} maxlength="100" >
            </div>
            <div class="form-group">
                Special request(optional)
                {% if not for_confimation_readonly %}
                <small class="form-text text-muted" style="float: right ;">(Maximum length of 100 character)</small>
                {% endif %}
                <input class="form-control" name="message" placeholder="Message" {% if message %}value="{{message}}" {%endif%} {% if for_confimation_readonly %} readonly {% endif %} maxlength="100">
                
            </div>

            <input hidden type="submit" id="Customer-details-form-submit" value="Submit">
        </form>
    </div>
</div>





{% else%}
<nav class="navbar sticky-top navbar-dark bg-dark justify-content-between">
    <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:menu' %}">Continue shopping</a>
</nav>
<h3>shopping cart is empty. Select some items first...</h3>
{% endif %}

{% endblock %}

orders/templates/orders/manage_admin_order.html
{% extends 'base_layout.html' %}


{% block title %}{{ block.super }} - manage orders{% endblock %}

{% block head %}
{% load static %}
<script src="{% static 'orders/manage_admin_order.js' %}"></script>
{% endblock %}


{% block content%}
<nav class="navbar sticky-top navbar-dark bg-dark">
    <a class="navbar-brand" href="#new_orders">New Orders</a>
    <a class="navbar-brand" href="#processing_orders">Currently Processing Orders</a>
    <a class="navbar-brand" href="#shipped_orders">On Way</a>
    <a class="navbar-brand" href="#delivered_orders">Delivered</a>
</nav>


<!-- do for new received orders -->
<br>
<h2 id="new_orders" class="menu-subheading">New Orders</h2>
{% if ordered_orders and ordered_orders|length > 0 %}

<!-- lets create a table with hidden borders so as to show the options. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 10%">Order ID</th>
            <th scope="col" style="width: 25%">Order time</th>
            <th scope="col" style="width: 15%">User</th>
            <th scope="col" style="width: 10%">Cost</th>
            <th scope="col" style="width: 20%">Message</th>
            <th scope="col" style="width: 20%">Status</th>
        </tr>
    </thead>
    <tbody>

        {% for order in ordered_orders %}
        <tr>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.id }}</a></td>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.ordertime }}</a></td>
            <td>{{ order.user }}</a></td>
            <td>{{ order.orderprice }}</td>
            <td>{{ order.message }}</td>
            <td><form name="update_status-{{ order.id }}" action="{% url 'orders:manage_admin_order' %}" onsubmit='return validateStatusUpdateForm("{{ order.id }}")' , method="POST">
                    {% csrf_token %}
                    <input hidden name="orderid" value="{{ order.id }}">
                    <input hidden name="original-status" value="Ordered">
                    <div class="input-group">
                        <select class="custom-select" name="status">
                            <option value="Cancel">Cancel</option>
                            <option selected value="Ordered">Ordered</option>
                            <option value="Preparing">Preparing</option>
                        </select>
                        <div class="input-group-append">
                            <input class="btn btn-sm btn-secondary" type="submit" value="Update">
                        </div>
                    </div>
                </form>
            </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else%}
<h5>No new order received...</h5>
{% endif %}

<br>



<!-- do for orders being prepared -->
<h2 id="processing_orders" class="menu-subheading">Currently Processing Orders</h2>
{% if preparing_orders and preparing_orders|length > 0 %}

<!-- lets create a table with hidden borders so as to show the options. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 10%">Order ID</th>
            <th scope="col" style="width: 25%">Order time</th>
            <th scope="col" style="width: 15%">User</th>
            <th scope="col" style="width: 10%">Cost</th>
            <th scope="col" style="width: 20%">Message</th>
            <th scope="col" style="width: 20%">Status</th>
        </tr>
    </thead>
    <tbody>

        {% for order in preparing_orders %}
        <tr>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.id }}</a></td>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.ordertime }}</a></td>
            <td>{{ order.user }}</a></td>
            <td>{{ order.orderprice }}</td>
            <td>{{ order.message }}</td>
            <td><form name="update_status-{{ order.id }}" action="{% url 'orders:manage_admin_order' %}" onsubmit='return validateStatusUpdateForm("{{ order.id }}")' , method="POST">
                {% csrf_token %}
                <input hidden name="orderid" value="{{ order.id }}">
                <input hidden name="original-status" value="Preparing">
                <div class="input-group">
                    <select class="custom-select" name="status">
                        <option value="Cancel">Cancel</option>
                        <option selected value="Preparing">Preparing</option>
                        <option value="On Way">On Way</option>
                    </select>
                    <div class="input-group-append">
                        <input class="btn btn-sm btn-secondary" type="submit" value="Update">
                    </div>
                </div>
            </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else%}
<h5>No order are currently being processed...</h5>
{% endif %}

<br>


<!-- do for orders being shipped -->
<h2 id="shipped_orders" class="menu-subheading">Orders On Way to customer</h2>
{% if shipped_orders and shipped_orders|length > 0 %}

<!-- lets create a table with hidden borders so as to show the options. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 10%">Order ID</th>
            <th scope="col" style="width: 25%">Order time</th>
            <th scope="col" style="width: 15%">User</th>
            <th scope="col" style="width: 10%">Cost</th>
            <th scope="col" style="width: 20%">Message</th>
            <th scope="col" style="width: 20%">Status</th>
        </tr>
    </thead>
    <tbody>

        {% for order in shipped_orders %}
        <tr>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.id }}</a></td>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.ordertime }}</a></td>
            <td>{{ order.user }}</a></td>
            <td>{{ order.orderprice }}</td>
            <td>{{ order.message }}</td>
            <td><form name="update_status-{{ order.id }}" action="{% url 'orders:manage_admin_order' %}" onsubmit='return validateStatusUpdateForm("{{ order.id }}")' , method="POST">
                {% csrf_token %}
                <input hidden name="orderid" value="{{ order.id }}">
                <input hidden name="original-status" value="On Way">
                <div class="input-group">
                    <select class="custom-select" name="status">
                        <option value="Cancel">Cancel</option>
                        <option selected value="On Way">On Way</option>
                        <option value="Delivered">Delivered</option>
                    </select>
                    <div class="input-group-append">
                        <input class="btn btn-sm btn-secondary" type="submit" value="Update">
                    </div>
                </div>
            </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else%}
<h5>No order are currently on the way to customer...</h5>
{% endif %}

<br>


<!-- do for fulfilled orders -->
<h2 id="delivered_orders" class="menu-subheading">Delivered Orders</h2>
{% if delivered_orders and delivered_orders|length > 0 %}

<!-- lets create a table with hidden borders so as to show the options. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 10%">Order ID</th>
            <th scope="col" style="width: 25%">Order time</th>
            <th scope="col" style="width: 15%">User</th>
            <th scope="col" style="width: 10%">Cost</th>
            <th scope="col" style="width: 20%">Message</th>
            <th scope="col" style="width: 20%">Status</th>
        </tr>
    </thead>
    <tbody>

        {% for order in delivered_orders %}
        <tr>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.id }}</a></td>
            <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.ordertime }}</a></td>
            <td>{{ order.user }}</a></td>
            <td>{{ order.orderprice }}</td>
            <td>{{ order.message }}</td>
            <td>{{ order.status }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}



{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'base_layout.html' %}


{% block title %}{{ block.super }} - order details{% endblock %}


{% block content%}
<nav class="navbar sticky-top navbar-dark bg-dark justify-content-between">
    <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:menu' %}">Continue shopping</a>
    <div>
    {% if user.is_superuser %}
    <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:manage_admin_order' %}">Manage Order</a>
    {% endif %}
    <a class="btn btn-sm btn-secondary my-2 my-sm-0" href="{% url 'orders:order_history' %}">Previous Orders</a>
    </div>
</nav>

<!-- lets create a table with hidden borders so as to show the options. -->
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 40%">Item (Size)</th>
            <th scope="col" style="width: 10%">Quantity</th>
            <th scope="col" style="width: 10%">Cost</th>
            <th scope="col" style="width: 40%">Addons</th>
        </tr>
    </thead>
    <tbody>

    {% for orderitem in orderdetail.orderitems.all %}
    <tr>
        <td>{% if orderitem.baseitem.pizza.crust %}{{ orderitem.baseitem.pizza.crust}} Pizza - {% endif %}
            {{ orderitem.baseitem.name }} {% if orderitem.baseitem.size %} ({{ orderitem.baseitem.size}} ){% endif %}
        </td>
        <td>{{ orderitem.quantity }}</td>
        <td>{{ orderitem.price }}</td>
        <td>{% if orderitem.toppings.count > 0 %}
            {% for topping in orderitem.toppings.all %}
            {% if forloop.last %}
            {{ topping.name }}
            {% else %}
            {{ topping.name }},
            {% endif %}
            {% endfor %}
            {% elif orderitem.subextra.count > 0 %}
            {% for extra in orderitem.subextra.all %}
            {% if forloop.last %}
            {{ extra.name }}
            {% else %}
            {{ extra.name }},
            {% endif %}
            {% endfor %}
            {% endif %}
        </td>
    </tr>
    {% endfor %}


    <!-- now lets write the cart total. -->
    <tr style="font-weight:bold">
        <td>Total</td>
        <td></td>
        <td>{{orderdetail.orderprice}}</td>
        <td></td>
        <td></td>
    </tr>
       
    </tbody>
</table>

<br>
<div class="row justify-content-center">
    <div style="width: 90%;" class="site-form">
        <h3>Customer details</h3>
        Contact
        <input class="form-control" name="contact" placeholder="Phone Number" readonly value="{{orderdetail.contact}}">
        Address
        <input class="form-control" name="address" placeholder="Address" readonly value="{{orderdetail.address}}">
        Special request
        <input class="form-control" name="message" placeholder="Message" readonly value="{{orderdetail.message}}">
    </div>
</div>

{% endblock %}