accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

orders/urls.py
"""order URL Configuration """

from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'orders'



urlpatterns = [
    path("", views.index, name="index"),
    url(r'^menu/$', views.index, name="menu"),
    url(r'^cart/$', views.cart_item_list, name="cart"),
    path('cart/delete_item/<int:cartitem_id>', views.delete_cart_item, name="delete_cart_item"),
    path('cart/confirm_order', views.confirm_order, name='confirm_order'),
    path('cart/place_order', views.place_order, name='place_order'),
    path('user/history', views.order_history, name="order_history"),
    path('user/order_detail/<int:order_id>', views.order_detail, name="order_detail"),
    path('cart/add_item/<int:item_id>', views.add_item, name='add_item'),
    path('manage/order', views.manage_admin_order, name='manage_admin_order'),

]

pizza/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]



urlpatterns += staticfiles_urlpatterns()

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Pizza Shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'navigationbar.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>

<body>

    <div class="NavigationBar">
        {% block navigationbarbar %}
        {% if user.is_superuser %}
        <a href="{% url 'orders:manage_admin_order' %}">Manage Order</a>
        {% endif %}
        <a href="{% url 'orders:menu' %}" >Menu</a>
        <a href="{% url 'orders:order_history' %}">Previous Orders</a>
        <a href="{% url 'orders:cart' %}">Cart
            {% if item_in_cart_count %}
            <span class="badge badge-pill badge-light" style="font-size: 60%; position: absolute;">{{item_in_cart_count}}</span>
            {% endif %}
        </a>

        {% if user.is_authenticated %}
            <form class="logout-link " action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button class="button right NavigationBarbutton" type="submit">Logout</button>
            </form>
        <a href="" class="right">Welcome, <strong>{{user}}.</strong></a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="right">Login</a>
        <a href="{% url 'accounts:signup' %}" class="right">Signup</a>
        {% endif %}
        {% endblock %}

    </div>

    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>


    <button id="movetotop" style="right:1.5em;bottom:2em; display: none;" class="btn btn-dark position-fixed">to top</button>

</body>


<script>
    document.addEventListener('DOMContentLoaded', () => {

        document.querySelector('#movetotop').onclick = () => {
            document.body.scrollTop = 0; // For Safari
            document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
        };

        window.onscroll = () => {
            if (document.body.scrollTop > 15 || document.documentElement.scrollTop > 15) {
                document.getElementById("movetotop").style.display = "block";
            } else {
                document.getElementById("movetotop").style.display = "none";
            };
        };
    });
</script>

</html>